### ISSUE TITLE
Add option to hide "post by {author}"

### ISSUE THREAD

**Issue by NathanCastle** [ritstudentgovernment/petitions#104]
We will want to be able to have a single user post all updates and responses, so having the 'update by' displayed isn't useful for us.

**Comment by petermikitsh** [comment]
How would you know who updated it then?

**Comment by NathanCastle** [comment]
They would have to sign at the end of the update, but most people have been doing that anyway.

Sent from Outlook on iOS




On Sun, Mar 6, 2016 at 4:00 PM -0800, "Peter Mikitsh" <notifications@github.com> wrote:





How would you know who updated it then?

---

**Comment by petermikitsh** [comment]
True, I think all the updates are manually signed. It might be easier to remove the feature from the UI rather than implement toggling state which would have to be persisted in the db.

**Comment by NathanCastle** [comment]
Resolved by #116
