### ISSUE TITLE
Remove response & update length limits

### ISSUE THREAD

**Issue by NathanCastle** [ritstudentgovernment/petitions#107]
There are concerns that the length limit for responses and updates is too short. The limits should either be extended significantly or eliminated.

**Comment by petermikitsh** [comment]
An aspect to consider is the verbosity of updates and responses, but then again that should probably be up to the author and not enforced by the software.

**Comment by NathanCastle** [comment]
I personally agree that authors should be cutting down the verbosity significantly, but it is a feature request and people are getting quite angsty about it. I think it is easier for me to remove the limits than to convince people to write succinctly, which is a little bit sad, but ¯\_(ツ)_/¯ .

**Comment by NathanCastle** [comment]
See #111 for a resolution to this. Length limits aren't fully removed, but extended to a reasonable length.
