### ISSUE TITLE
Search doesn't return responded issues

### ISSUE THREAD

**Issue by ceko** [ritstudentgovernment/petitions#118]
Is this by design?  For example, go to https://pawprints.rit.edu/petitions/xomY3GW43Q9D5igNQ with the title of Earlier Creative Industry Day.  If you search for that on https://pawprints.rit.edu/search it doesn't show up.

**Comment by NathanCastle** [comment]
Good catch. I don't think that's by design and it is definitely new behavior. Will need to investigate to find a fix.

**Comment by ceko** [comment]
I probably caused it by switching to the new search box, at least on my local copy I did.

**Comment by NathanCastle** [comment]
Should be resolved in 097b332d4c51781b653b0dbe454cb328649b45a0

**Comment by NathanCastle** [comment]
This is resolved and in master.
