### ISSUE TITLE
Add header for sending people to the PawPrints discussion group on facebook

### ISSUE THREAD

**Issue by lheigl** [ritstudentgovernment/petitions#126]

**Comment by NathanCastle** [comment]
Where?

**Comment by lheigl** [comment]
![capture](https://cloud.githubusercontent.com/assets/7872901/16307756/6dec0068-3930-11e6-9e7c-ffd2c81c2300.PNG)

Something like this was what I had in mind.

**Comment by NathanCastle** [comment]
I'm not sure how I feel about a banner... How would you feel about putting it in the petition sidebar? 

<img width="413" alt="screen shot 2016-06-23 at 10 06 49 pm" src="https://cloud.githubusercontent.com/assets/5623999/16325777/13b8cc52-398f-11e6-92d7-d3ca1d19da28.png">

**Comment by lheigl** [comment]
Agreed, that looks much better.

**Comment by NathanCastle** [comment]
Resolved in d448eaf
