### ISSUE TITLE
Display exact dates instead of approximations

### ISSUE THREAD

**Issue by lheigl** [ritstudentgovernment/petitions#128]

**Comment by NathanCastle** [comment]
Where do you want this and for which dates?

**Comment by lheigl** [comment]
Anything that would be displayed as less than 3 months ago. 
![capture1](https://cloud.githubusercontent.com/assets/7872901/16307948/279f71f2-3931-11e6-9785-23459179f7ce.PNG)

So in this example the box would be changed to say an exact date, but the underlined one would display 9 months ago

**Comment by NathanCastle** [comment]
I wonder about the usability of this. The library that handles these dates tends to give less precision the further out you go, so there are lots and lots of things that are going to be 'a year ago', whereas more recent things tend to be a little more precise. 

I like this article about timestamps: http://uxmovement.com/content/absolute-vs-relative-timestamps-when-to-use-which/ 

In the case of PawPrints it is both a rapidly changing media site (relative times preferred) and a historical document archive (absolute times preferred). 

How would you feel about showing the relative timestamps in those places, with a tooltip icon next to it that reveals the exact date and time? I think it also makes sense to add the full absolute date & time to the card on the right, as that has some of the more detailed information and has plenty of space for more details. 

It would look something like this:
<img width="281" alt="screen shot 2016-06-23 at 9 56 33 pm" src="https://cloud.githubusercontent.com/assets/5623999/16325605/7dfcdf06-398d-11e6-9039-5a460df4f9c1.png">

Does that work for you?

**Comment by NathanCastle** [comment]
This is another option: 

![image](https://cloud.githubusercontent.com/assets/5623999/16326021/307eeab8-3991-11e6-9834-7ba02ad4cd62.png)

(shamelessly copied from the article referenced above)

**Comment by lheigl** [comment]
The automatic conversion in the article is along the lines of what I was thinking, but if the library doesn't provide enough precision we might not be able to do that.

I think the tooltip timestamps would be best, as long as we include the the icon you mentioned, or the dashed line.
