### ISSUE TITLE
Offer way to post anonymous petitions

### ISSUE THREAD

**Issue by Undeterminant** [ritstudentgovernment/petitions#13]
Removing names allows students to make petitions that they'd otherwise be uncomfortable mentioning publicly: for example, the one on handling sexual assaults would probably not have been made by someone who had actually been sexually assaulted on campus, because they wouldn't want to be known as the person that brought it up.

Names would still be kept on the website in case someone says something where disciplinary action needs to be taken, but otherwise, it seems like a good idea to not tag everything with a name. People can still come out and say "hey! I made this; sign it!" but they don't have to if they don't want to.

Obviously, this would also remove the functionality to search by authors of petitions as well.

**Comment by volfco** [comment]
I think the 2nd implementation is the way to go. If someone needs to be truly anonymous, then this service is not the right way to voice the complaint.

**Comment by NathanCastle** [comment]
The ultimate decision for this was to encourage students to contact a friend or SG representative to post on their behalf if they don't want to be associated with a petition.
