### ISSUE TITLE
Indication on card for "signed"

### ISSUE THREAD

**Issue by regdoug** [ritstudentgovernment/petitions#26]
I think that a visual indication of whether you signed the petition would be helpful for the card view.  My suggestion would be a different border (make the card look slightly recessed?). A border would be subtle enough not to clutter the interface and does not interfere with existing status marks.

I don't know if this would have adverse performance implications because I haven't really looked at the model, so that could be an obstacle.

If the performance hit isn't likely to be significant and the visual effect can be agreed upon, I can PR this.

- [ ] On the petition list publication, publish the upvoters array. (0.25 hr)
- [ ] In front-end logic, determine if the current user is $in the upvoters array. If so, show a badge signifying the signed state. (0.5 hr)

Total hours: 0.75 hr

**Comment by Undeterminant** [comment]
How about adding "signed" as the first in the tag list, except maybe make it brown or grey to make it stand out?

**Comment by NathanCastle** [comment]
This has been implemented and is in dev.
