### ISSUE TITLE
Add ability to distinguish between "In Progress" petitions that do and do not have a status update.

### ISSUE THREAD

**Issue by aaronmaxlevy** [ritstudentgovernment/petitions#27]
It would be nice if I could see a list of petitions that haven't been responded to yet ("In Progress") but have received status updates.

**Comment by petermikitsh** [comment]
@aaronmaxlevy I'm going to close this issue. The only other way to ameliorate this would be to create a migration for all status updates that were marked 'in progress' (but have no updates) to 'goal reached' status.

However, I'd prefer that we just remained transparent with the student body in a more timely manner (as we should). I'll continue to push for more frequent posting of updates.
