### ISSUE TITLE
Authorize signature privileges for authenticated users

### ISSUE THREAD

**Issue by petermikitsh** [ritstudentgovernment/petitions#29]
Some users, such as alumni, should not be able to sign petitions. The idea is that there are finite amount of resources that exist to respond to petitions, and we want to most adequately use our resources to respond to only the needs of currently active members of the community, e.g., currently enrolled students and staff.

Possible implementation: using the `roles` package, create a role that signifies the right to sign a petition. If the user account does not have the right, then show an error message saying the user cannot sign petitions.

RIT implementation: All user sessions should be wiped from the production database (see http://stackoverflow.com/questions/20515989/how-can-i-log-out-a-user-from-the-server-in-meteor-js):

```javascript
Meteor.users.update({}, {$set : { "resume.loginTokens" : [] }, {multi:true});
```

Then, on login, in the LDAP callback, examine the `ritEduAccountType` ldap attribute. If the attribute is not `alumni`, then add the signature role.

**Comment by NathanCastle** [comment]
Due to how specific this is to RIT, and due to the lack of a policy on who shouldn't be able to sign (who says alumni are less relevant than faculty?), this issue will be closed.
