### ISSUE TITLE
Mark petitions as viewable only to administators

### ISSUE THREAD

**Issue by petermikitsh** [ritstudentgovernment/petitions#34]
Mark a petition such that it can only be viewed if the authenticated user has admin rights. These petitions are not accessible via the API when marked this state. This state is also reversible.

- [x] Add a boolean field to the Petition model (0.25 hr)
- [x] Create a migration to set value to false on all previous petitions (0.25 hr)
- [x] Add access controls to publications and API endpoints to respect the admin_only property (3 hr)
- [x] Create a UI and update endpoint for admins to manage this setting (1 hr)

Total hours: 4.5 hrs

**Comment by petermikitsh** [comment]
@NathanCastle What should we show for this use case, in the event the user tries to access the petition directly via its URL (e.g., pawprints.rit.edu/petitions/abc123...)? We could show the generic 404 page.

**Comment by NathanCastle** [comment]
@petermikitsh perhaps we could allow the administrator to input a short explanation of why the content is hidden, and display that? Alternatively I think just a 404 is fine.

**Comment by petermikitsh** [comment]
@NathanCastle For right now, I'll implement this as a plain 404. I'll bring this up at the next committee meeting. If the committee moves for additional functionality, we can add it to the backlog.

**Comment by petermikitsh** [comment]
@NathanCastle To clarify, admin users will still be access all petitions (no 404 errors will be shown to these authorized users).

**Comment by petermikitsh** [comment]
Actual Implementation: ~2 hours
