### ISSUE TITLE
Not receiving update emails

### ISSUE THREAD

**Issue by zachberger** [ritstudentgovernment/petitions#36]
I have checked 

    E-mail me when new status updates are posted on petitions I sign, such as:

    The formation of SG committees to investigate petition topics. 
    Reachout efforts to members of the Administration.

and have not been receiving these emails

**Comment by petermikitsh** [comment]
@zachberger I'm going to close this issue. From my manual testing, I wasn't able to reproduce it. If you have any additional concerns, let me know.
