### ISSUE TITLE
Extra reporting options.

### ISSUE THREAD

**Issue by Undeterminant** [ritstudentgovernment/petitions#44]
Petitions like [this one](https://pawprints.rit.edu/petitions/iFdAyRe7cMAfYGmsS) cannot be resolved because this is NY's problem, not RIT's. There should be an option to flag a petition for "The petition makes a request that RIT cannot resolve."

Petitions like [this one](https://pawprints.rit.edu/petitions/mkufH82ieyYoH4e5B) are already resolved. There should be an option to flag a petition for "The petition is already resolved."

**Comment by NathanCastle** [comment]
One important aspect of PawPrints is educating students why things are the way that they are. In this case, it is important that students understand that this is a limitation of NY state, for example. 

Additionally, SG has made significant moves to expand its advocacy mission. Part of that includes getting involved with state-level legislation. In the future, SG may take more actions to support policy changes at the state level. 

Thanks for the suggestion, though. I appreciate your interest in the project! :)
