### ISSUE TITLE
Add option to sort petitions by latest signature

### ISSUE THREAD

**Issue by Undeterminant** [ritstudentgovernment/petitions#50]

**Comment by petermikitsh** [comment]
Interesting concept. We don't currently keep track of that.

**Comment by petermikitsh** [comment]
We would need to create a migration to update the `Post` model to include a field for a last signed datetime, e.g., `lastSignedAt`. We could initialize this new field to the petition `createdAt` datetime for existing petitions.

**Comment by NathanCastle** [comment]
Resolved in a5d8575e9c12f91864e9d94ae480f46b2498089c
