### ISSUE TITLE
Loading Indicators

### ISSUE THREAD

**Issue by volfco** [ritstudentgovernment/petitions#55]
There are no loading indicators when preforming an action on the site. On slow internet connections, there is no indication that a link has been clicked, or a form has been submitted. 

A simple loading indicator would be nice.

**Comment by petermikitsh** [comment]
A list of all the workflows missing loading indicators would be helpful. For example, here is the loading indicator shown when reporting a petition:

![img](https://cloud.githubusercontent.com/assets/1571918/6837615/c6a59b2e-d324-11e4-8e45-b2235e91a0fe.png)

**Comment by NathanCastle** [comment]
This is a good idea, but I think it is more important to work on making the app faster. There are opportunities to improve performance.
