### ISSUE TITLE
Users can edit their name

### ISSUE THREAD

**Issue by petermikitsh** [ritstudentgovernment/petitions#56]
Via the console, using:

`Meteor.users.update(Meteor.userId(), {...}});`,

users can change any property in their `profile` object. Note that this issue only allows the currently logged in user to edit their own User document. Meteor was designed to allow users to manipulate the `profile` object. @gbprz Does your implementation allow users to edit their name?

**Comment by gbprz** [comment]
While we don't currently have any way for users to edit their details on the profile page, I tried manipulating the profile object via the Chrome console and I can confirm that I was allowed to change my profile info using the method you mentioned:

``` 
Meteor.users.update(Meteor.userId(), { $set: {profile: {"name" : "perezg2", "displayName" : "Gabe Perez", "initials" : "GP", "sn" : "perezg2", "givenName" : "perezg2" }}});
```
