### ISSUE TITLE
Add "Petitions I've Signed " View

### ISSUE THREAD

**Issue by KevinMGranger** [ritstudentgovernment/petitions#57]
As a user, I want to easily view a list of all petitions I've signed.

If this functionality is already possible, it could benefit from being more obviously presented (even if it's a link to a pre-populated search)

**Comment by petermikitsh** [comment]
Thanks for opening this issue. We've heard this feature request in the past. It's something we should provide. I have added it to our backlog.

**Comment by NathanCastle** [comment]
Resolved in #94
