### ISSUE TITLE
HTML tags showing up in metadata tags

### ISSUE THREAD

**Issue by petermikitsh** [ritstudentgovernment/petitions#59]
HTML tags should be stripped from the metadata tags.

HTML inserted into the metatags:

![screen shot 2015-04-23 at 3 08 59 pm](https://cloud.githubusercontent.com/assets/1571918/7305284/b866c8be-e9ca-11e4-9a1f-93d25e35b505.png)

Not stripped from FB shares:

![screen shot 2015-04-23 at 3 06 17 pm](https://cloud.githubusercontent.com/assets/1571918/7305227/4ed8b6dc-e9ca-11e4-9818-d47d9f2efe01.png)

**Comment by NathanCastle** [comment]
Resolved in 563d09e63fb2177fac2ebb6c2f3ba42d3a245869
