### ISSUE TITLE
Text input fields randomly erasing characters as they're typed

### ISSUE THREAD

**Issue by YawarRaza7349** [ritstudentgovernment/petitions#60]
When typing into either the "Petition Name" or "Petition Descriptions" textbox, if I'm typing quickly, sometimes characters will be erased from the end of the string. Copy-pasting the text into a text editor shows the same erased string that I see in the textbox, so this isn't a rendering issue. I'm on Google Chrome version 42.0.2311.152 m on Windows 7.

**Comment by petermikitsh** [comment]
Thanks for the bug report. This will probably be resolved when #51 is worked on.

**Comment by ntratcliff** [comment]
I'm also having issues with characters being erased when I type too fast in the name or description box.

Chrome 47.0.2526.111 m on Win10

**Comment by ceko** [comment]
I've seen this issue in Chrome as well on the develop branch.

**Comment by ceko** [comment]
Pull request that fixes the issue:  https://github.com/ritstudentgovernment/petitions/pull/90

**Comment by NathanCastle** [comment]
Fixed in #90
