### ISSUE TITLE
Can't get to the footer easily due to lazy loading

### ISSUE THREAD

**Issue by tibsar** [ritstudentgovernment/petitions#63]
I wanted to get to the links at the footer but had to scroll through 422 petitions to get there.  Having the footer is nice, but with lazy loading it's a pain to get to.  It would be awesome to add the links elsewhere as well.

**Comment by petermikitsh** [comment]
I think it'd be best to simply hide the footer on non-infinite scroll views.

**Comment by NathanCastle** [comment]
I'm going to close this as won't fix right now - the footer is easily visible on the about page, and I don't think the footer's visibility is critically important. As the service continues to grow, pagination may be introduced, but for now it isn't a priority. 

Thank you for your feedback and interest in the service. :)
