### ISSUE TITLE
Long string overflow not contained within cards

### ISSUE THREAD

**Issue by petermikitsh** [ritstudentgovernment/petitions#70]
See example of bug below.

<img width="1065" alt="screen shot 2015-09-24 at 9 22 24 am" src="https://cloud.githubusercontent.com/assets/1571918/10079259/d7d69674-629d-11e5-99d5-0edb8cffcba3.png">

You could fix this with this css:

```css
word-wrap: break-word;
````

**Comment by James-Reilly** [comment]
This is now fixed in the latest build. Thanks Pete!
