### ISSUE TITLE
Email alert after moderation error

### ISSUE THREAD

**Issue by ceko** [ritstudentgovernment/petitions#87]
If the email setting isn't set up properly or the email server isn't receiving connections, a moderator gets a generic error when approving a petition.  I'm going to create a pull request to fix this minor issue, I just wanted to reference this issue when I do it.

**Comment by ceko** [comment]
In my recent pull request https://github.com/ritstudentgovernment/petitions/pull/88 I have a fix for this, since all emails route through the same object, it can return a Meteor.error when the SMTP server is unreachable.

**Comment by NathanCastle** [comment]
Resolved in #88
