### ISSUE TITLE
Differentiate petition tiles for petitions that are sitting in the moderation queue

### ISSUE THREAD

**Issue by NathanCastle** [ritstudentgovernment/petitions#95]
For logged in moderators, petitions that are waiting to be approved appear in the regular views as if they were already approved. There should be some visual indicator that it isn't approved yet.

**Comment by ceko** [comment]
What did you have in mind?

**Comment by NathanCastle** [comment]
Resolved in #114 .

**Comment by NathanCastle** [comment]
<img width="559" alt="screen shot 2016-03-21 at 8 34 10 pm" src="https://cloud.githubusercontent.com/assets/5623999/13938693/32a5e756-efa4-11e5-9adb-6bbe5695c0cf.png">

Example of what this looks like.
